# Using Ubuntu 18.04
FROM ubuntu:18.04
# Information about me
MAINTAINER denys naida <NaidaDV@nmu.one>
# Updating and upgrading 
RUN apt-get update && apt-get upgrade -y && apt-get install maven -y && apt-get install openjdk-11-jdk -y
RUN mvn package -f /project/springbootwebapp-master/pom.xml
ENTRYPOINT java -jar /project/springbootwebapp-master/target/spring-boot-web-0.0.1-SNAPSHOT.jar