pipeline {
    
	agent {
		node {
			label 'slave_homework'
	}
}
	tools { 
        maven 'maven 3.6.3'
		jdk 'jdk8'
}
    stages { 
		stage('Check jdk and maven') {
			steps {
				sh "java -version"
				sh "mvn -v"
	}
}
		stage('Compiling web-app') {
			steps {
				sh "mvn package -f 'second_homework_java_web_app/springbootwebapp/pom.xml'"
	}
}
		stage('Build container') {
			steps {
				script {
					docker.build("image:build_${env.BUILD_ID}", "second_homework_java_web_app/")
        }
	}
}
		stage('Run container with web-app') {
			steps {
				sh "docker run -itd -p '8090:8080' --name 'container_${env.BUILD_ID}' 'image:build_${env.BUILD_ID}'"
	}
}
		stage('Test web-app') {
			steps {
				sh "curl localhost:8090"
		}
	}            
}
	/*post('Cleaning workspace') { 
        always {
			sh "docker stop 'container_${env.BUILD_ID}' && docker rm 'container_${env.BUILD_ID}'"
			sh "docker rmi -f 'image:build_${env.BUILD_ID}'"
			cleanWs()
		}
	}*/
}
