pipeline {
    
	agent {
	node {
        label 'master'
	}
	tools { 
        maven 'maven 3.6.3' 
        jdk 'jdk8' 
    }
}
            stages {
                
    stage('Check maven') {
        steps {
            sh "mvn -v"
	}
}
                    
    /*stage('Compiling web-app') {
        steps {
            sh "docker run -itd -p '8081:8081' --name 'container_${env.BUILD_ID}' 'naidadv/courses_homework2:build_${env.BUILD_ID}'"
            sh "curl localhost:8081"
            sh "docker stop 'container_${env.BUILD_ID}' && docker rm 'container_${env.BUILD_ID}'"
        }
}
                            
    
}*/
	post { 
        always {
		sh "docker rmi $registry:build_${env.BUILD_ID}"
		sh "docker rmi -f 'registry.hub.docker.com/naidadv/courses_homework2:build_${env.BUILD_ID}'"
		cleanWs()
		}
	}
}