# Using ubuntu 20.04 LaTex
FROM ubuntu:20.04

# Information about me
MAINTAINER denys naida <NaidaDV@nmu.one>

# Updating, upgrading && installing reqired soft
RUN apt-get update && apt-get upgrade -y && apt-get install nginx -y && apt-get install net-tools -y && apt-get install openjdk-11-jdk -y && apt-get install sudo -y && apt-get install curl -y

# Adding user with privileges
RUN useradd -s /bin/bash -d /home/main_admin -m --no-log-init main_admin && usermod -aG sudo main_admin
RUN echo "main_admin:madmin" | chpasswd

# Adding user for nginx
RUN groupadd nginx_admin && useradd -g nginx_admin -s /bin/bash -d /etc/nginx -m  --no-log-init nginx_admin && usermod -aG www-data main_admin
RUN echo "nginx_admin:nadmin" | chpasswd

# Changing nginx.conf
RUN rm /etc/nginx/nginx.conf
COPY ./nginx.conf /etc/nginx/nginx.conf

#Adding rights to nginx_user
RUN chown -R nginx_admin /etc/nginx/ && chown -R nginx_admin /var/log/nginx/ && chown -R nginx_admin /var/lib/nginx/ && chown -R nginx_admin /run
RUN chmod -R u+w /etc/nginx/ && chmod -R u+w /var/log/nginx/ && chmod -R u+w /var/lib/nginx/ && chmod -R u+w /run

USER nginx_admin
CMD ["nginx", "-g", "daemon off;"]